### ISSUE TITLE
Private Key Location

### ISSUE THREAD

**Issue by briandcosta** [relme/keyup#4]
Hey,

Finally got around to accepting the beta. I'm wondering when it asks for our Private Key, is that stored on the device or a server?

--Brian

**Comment by briandcosta** [comment]
I see the following in the FAQ under what is "stored on the device" so I'm assuming nothing takes place on a server. Everything happens in-device: "Inside the encrypted sqlite database we store your private key encrypted again using TripleSec just to be extra safe."

**Comment by gabriel** [comment]
If you create a new keybase.io account, by default it stores the TripleSec'ed key on the keybase.io server.

If you import your key, then its only saved on the device (again always TripleSec'ed).

I'll update the FAQ and maybe add a feature request to give the user an option on signup to not save to the server. (The reason its enabled by default is so that there is a "backup" of the key, if your phone crashes or the app is removed.)

**Comment by briandcosta** [comment]
Hey Gabriel (or Gab?)

Yeah, I know Keybase gives that option...but then it puts my Private Key out of my control...even if its encrypted on a secure server...so KB only has my Public Key. It just gives me more control over where my Key lives. I'm sure you understand :)

**Comment by gabriel** [comment]
yeah exactly... if imported it stays on the device

**Comment by briandcosta** [comment]
Hey Gab,

Just an idea, does Keyup have Documents access via iTunes? Might be a good
feature to add for those that don't have/want their Private Key hosted on
Keybase.

--Brian

**Comment by gabriel** [comment]
yeah thought about that.. created ticket here:
https://github.com/relme/keyup/issues/6

**Comment by briandcosta** [comment]
Shiny :)
